# Generated by Django 5.0.6 on 2024-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя", max_length=50, verbose_name="Имя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите телефон(не более 10 символов)",
                        max_length=10,
                        verbose_name="Телефон",
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ("name",),
            },
        ),
    ]
