# Generated by Django 5.0.6 on 2024-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.BigIntegerField(
                help_text="Введите телефон(не более 10 символов)",
                max_length=10,
                verbose_name="Телефон",
            ),
        ),
    ]
