# Generated by Django 5.0.6 on 2024-06-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите содержимое", verbose_name="Содержимое"
                    ),
                ),
                (
                    "image_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публикация"),
                ),
                (
                    "count_view",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите строку названия категории",
                        max_length=50,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание категории",
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите строку названия товара",
                        max_length=100,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "image_preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото товара",
                        null=True,
                        upload_to="products/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        help_text="Введите строку стоимости товара",
                        verbose_name="Стоимость товара",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ("name",),
            },
        ),
    ]
