# Generated by Django 5.0.6 on 2024-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(max_length=150, unique=True, verbose_name="Slug"),
        ),
    ]
