# Generated by Django 5.0.6 on 2024-06-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("pk",),
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
